# Generated by Django 5.1.2 on 2025-04-20 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='therapists.therapist'),
        ),
    ]
