# Generated by Django 5.1.2 on 2025-03-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
