services:
  app:
    build: .
    ports:
      - "8003:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
    - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - psychology_data:/var/lib/postgresql/data

volumes:
  psychology_data: