# Generated by Django 5.1.2 on 2025-03-31 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_therapist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
