# Generated by Django 5.1.2 on 2025-03-31 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0003_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
    ]
