# Generated by Django 5.1.2 on 2025-03-28 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SCHEDULED', 'Agendada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada'), ('RESCHEDULED', 'Reagendada')], default='PENDING', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('patients', models.ManyToManyField(through='therapy.TherapyParticipant', to='users.patient')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.therapist')),
            ],
        ),
        migrations.AddField(
            model_name='therapyparticipant',
            name='therapy_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.therapysession'),
        ),
        migrations.AlterUniqueTogether(
            name='therapyparticipant',
            unique_together={('therapy_session', 'patient')},
        ),
    ]
