# Generated by Django 5.1.2 on 2025-03-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
